name: Build and push docker image

# Trigger: whenever something push on Master branch
on:
  push:
    branches: ["master"]
  pull_request: 
    branches: ["master"]
    types: [opened, synchronize, reopened]

jobs:
  build-and-push:
    runs-on: ubuntu-latest #Using Github Linux server

    steps:
      #1. Checkout Code
      - name: Checkout code
        uses: actions/checkout@v4

      #2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
          cache: 'npm'

      #3. Install Dependencies
      - name: Install Dependencies
        run: npm ci

      #4. Quality Guard (Linting)
      - name: Run Linting
        run: npm run lint

      #6. Docker buildx setup
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      #7. Login to docker hub
      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #8. Build Image and Push
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ngrx-store:latest

  # Deploy to AWS
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          scripts: |
            #1. Pull Latest image
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/ngrx-store:latest

            #2. Stop and remove old container
            sudo docker stop angular-app || true
            sudo docker rm angular-app || true

            #3. Run New container and name it angular-app
            sudo docker run -d -p 80:80 --name angular-app ${{ secrets.DOCKER_USERNAME }}/ngrx-store:latest