name: Build and push docker image

# Trigger: whenever something push on Master branch
on:
  push:
    branches: ["Master"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest #Using Github Linux server

    steps:
      #1. Checkout Code
      - name: Checkout code
        uses: actions/checkout@v4

      #2. Docker buildx setup
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      #3. Login to docker hub
      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #4. Build Image and Push
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ngrx-store:latest
